name: UniProBudget CI

on:
 push:
   branches: [main]

 workflow_dispatch:

jobs:
 build-and-test:
   runs-on: ubuntu-latest

   defaults:
     run:
       working-directory: UniProBudget

   steps:
   - uses: actions/checkout@v4

   - name: Setup Java
     uses: actions/setup-java@v4
     with:
       distribution: zulu
       java-version: 17
       cache: gradle

   - name: Make gradlew executable
     run: chmod +x gradlew

   - name: Run Unit Tests
     run: ./gradlew test

   - name: Run Lint
     run: ./gradlew lint

   - name: Build Debug APK
     run: ./gradlew assembleDebug

   - name: Upload APK
     uses: actions/upload-artifact@v4
     with:
       name: Debug-APK
       path: UniProBudget/app/build/outputs/apk/debug/
