name: UniProBudget CI Automated Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: UniProBudget

    steps:

     
      - name: Checkout Repository
        uses: actions/checkout@v4

      
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

     
      - name: Make gradlew executable
        run: chmod +x gradlew

    
      - name: Run Unit Tests
        run: ./gradlew test

    
      - name: Run Lint Checks
        run: ./gradlew lint

     
      - name: Run Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: |
            cd UniProBudget
            ./gradlew connectedAndroidTest

     
      - name: Build Debug APK
        run: ./gradlew assembleDebug

     
      - name: Build Release APK
        run: ./gradlew assembleRelease

     
      - name: Build App Bundle
        run: ./gradlew bundleRelease

      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Debug-APK
          path: UniProBudget/app/build/outputs/apk/debug/

      
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: UniProBudget/app/build/outputs/apk/release/

    
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: Release-AAB
          path: UniProBudget/app/build/outputs/bundle/release/
